2-DIMENTIONAL ARRAYS

Accessing and Changing specific elements, rows, columns etc

In [23]:
import numpy as np
import sys

In [24]:
A = np.array([
    [1,2,3,4,5,6,7],
    [2,4,5,7,8,4,8]
    ])
print(A)

[[1 2 3 4 5 6 7]
 [2 4 5 7 8 4 8]]


In [25]:
# Checking shape
A.shape

(2, 7)

Get specific element

In [26]:
# The traditional way
A[0][6]
# The efficient and pro way idx[row/horizontal, column/vertical]
A[0,6]

7

In [27]:
# Slicing [start_idx:end_idx:separator]
A[1, 2:5:2]

array([5, 8])

In [28]:
# Replacing elements
A[1,5] = 20
print(A)

[[ 1  2  3  4  5  6  7]
 [ 2  4  5  7  8 20  8]]


In [29]:
# Replace same index position in both arrays
A[:, 2] = 55
print(A)
print('-------------------')

# Replace same index postion with different numbers
A[:, 2] = [11,22]
print(A)

[[ 1  2 55  4  5  6  7]
 [ 2  4 55  7  8 20  8]]
-------------------
[[ 1  2 11  4  5  6  7]
 [ 2  4 22  7  8 20  8]]


3-DIMENTIONAL ARRAYS

In [30]:
d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Get Element in a Dimension

In [31]:
# outside in - [dim,dim_arr,dim_arr_idx]
d[0,1,1]

4

In [32]:
# Change element
d[1,0,1] = 4
print(d)

[[[1 2]
  [3 4]]

 [[5 4]
  [7 8]]]


In [33]:
# slicing [all_dim:2nd_arr:all_idx]
d[:,1,:]
print(d)
print('-----------------')

[[[1 2]
  [3 4]]

 [[5 4]
  [7 8]]]
-----------------


In [34]:
# assign value
d[:,1,:] = [22,44], [33,88]
print(d)

[[[ 1  2]
  [22 44]]

 [[ 5  4]
  [33 88]]]


In [36]:
# The shape of the dimensions are always fixed
# Arent dynamic else there will be a shape mismatch(now undestand dimension mismatch error in LLMs!)
# Try fitting an elephant in a jar
d[:,1,:] = [22,44], [33,88], [77, 11]
print(d)

ValueError: could not broadcast input array from shape (3,2) into shape (2,2)