# Initializing Different Array Datatypes

In [1]:
import numpy as np

In [2]:
a = np.array([
    [[1, 3], [4, 5]],
    [[7, 8], [3, 9]]
])

### Dimensions
(num_of_dim, num_of_rows/array_per_dim, num_of_columns_per_row/array)

In [3]:
# All 0s matrix | dtype can be specified
# np.zeros(5)
# np.zeros((2,2)) # 2D
# np.zeros((2,2,3)) # 3D
np.zeros((2,2,3,4), dtype='int16') # 4D

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int16)

In [4]:
# All 1s matrix
# np.ones(5)
# np.ones((2,2)) # 2D
# np.ones((2,2,3)) # 3D
np.ones((2,2,3,4), dtype='int16') # 4D

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]], dtype=int16)

In [5]:
# Any other number
# Takes 2 parameters((shape), num_to_input)
np.full((2,3,4), 7, dtype='float32')

array([[[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]],

       [[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]], dtype=float32)

In [6]:
# create array and inheritt shape from already built array
# way 1
np.full(a.shape, 4)
np.full_like(a, 2)

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [7]:
# Random FP numbers
np.random.rand(4,2,3) # 4 Rows and 2 Columns
# A nice way to visualize weights lol

array([[[0.38072069, 0.73957544, 0.47215872],
        [0.13036259, 0.81473306, 0.2928876 ]],

       [[0.17468619, 0.25374974, 0.66832433],
        [0.35276195, 0.26440989, 0.02283673]],

       [[0.59177991, 0.29245813, 0.09533085],
        [0.99045453, 0.85177761, 0.27516643]],

       [[0.07163294, 0.39017066, 0.97111808],
        [0.94890437, 0.07358107, 0.08628441]]])

In [8]:
# Random FP with shape inheritance
np.random.random_sample(a.shape)

array([[[0.47956442, 0.04677953],
        [0.64559463, 0.38699751]],

       [[0.75088084, 0.54007815],
        [0.54361426, 0.86735042]]])

In [9]:
# Random intergers ith shape inheritance
np.random.randint(0, 100, a.shape)

array([[[76, 72],
        [96, 74]],

       [[ 2, 92],
        [37, 15]]])

In [10]:
# Random int with specified shape
np.random.randint(100, size=(4,7))

array([[75,  2, 59, 30, 11, 70, 74],
       [46, 88,  7, 16, 48, 61, 68],
       [ 3, 46, 99, 58, 49, 42, 19],
       [11, 75, 29,  4, 25, 74, 99]])

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.randint(-4,8, size=(3,3))

array([[ 4,  0,  5],
       [ 4,  5, -2],
       [-4,  7,  5]])

In [20]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [36]:
# random repeat
arr1 = np.zeros((5,5), dtype=int)

arr1[0, :] = arr1[-1, :] = arr1[:, 0] = arr1[:, -1] = 1
arr1[2, 2] = 9
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
hello