# Initializing Different Array Datatypes

In [2]:
import numpy as np

In [7]:
a = np.array([
    [[1, 3], [4, 5]],
    [[7, 8], [3, 9]]
])

### Dimensions
(num_of_dim, num_of_rows/array_per_dim, num_of_columns_per_row/array)

In [3]:
# All 0s matrix | dtype can be specified
# np.zeros(5)
# np.zeros((2,2)) # 2D
# np.zeros((2,2,3)) # 3D
np.zeros((2,2,3,4), dtype='int16') # 4D

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int16)

In [4]:
# All 1s matrix
# np.ones(5)
# np.ones((2,2)) # 2D
# np.ones((2,2,3)) # 3D
np.ones((2,2,3,4), dtype='int16') # 4D

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]], dtype=int16)

In [6]:
# Any other number
# Takes 2 parameters((shape), num_to_input)
np.full((2,3,4), 7, dtype='float32')

array([[[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]],

       [[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]], dtype=float32)

In [11]:
# create array and inheritt shape from already built array
# way 1
np.full(a.shape, 4)
np.full_like(a, 2)

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [ ]:
# Random decimal numbers