# Linear Algebra, Matrices & Statistics

In [1]:
import numpy as np

### Rule!
#### no. columns in array 1 == no. of rows in array 2
#### Num of Colums of first array must be equal to num of rows in second array

In [2]:
# Create matrix of ones
a = np.ones((2,3))
print(a)

# Create matrix of twos
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


### Multiply both matrices

In [4]:
c = np.matmul(a, b)
print(c)

[[6. 6.]
 [6. 6.]]


### Find Determinant of a Matrix

In [6]:
# Create identity matrix
d = np.identity(3)

# Get determinant -- This would give us 1
np.linalg.det(d)

1.0

https://numpy.org/doc/stable/reference/routines.linalg.html

#### Statistics