Import NumPy as object


In [1]:
import numpy as np
import sys

Basic array initialization


In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


2D array with FP


In [7]:
# Must wrap multi-dimentional arrays as a matrice
b = np.array([
    [1.3, 8.5, 7.8], [4.9, 5.0, 3.2]
    ])
print(b)

[[1.3 8.5 7.8]
 [4.9 5.  3.2]]


Check Number of Dimensions


In [9]:
a.ndim

1

In [10]:
b.ndim

2

Get shape \
Shape returns the size of the array as a vector/tuple (rows, columns)


In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

Get Memory


In [13]:
# Check Type
print(a.dtype)
print(b.dtype)

int64
float64


Set Explicit Datatype


In [17]:
c = np.array([2, 8, 12], dtype='int16')
print(c)
c.dtype

[ 2  8 12]


dtype('int16')

In [20]:
# Get dtype size
print(a.itemsize)
print(b.itemsize)
print(c.itemsize) # This is lower because we explicitly set the int type
# Memory is 64 to allow for large figures, yet can be a waste
# so explicitly setting it can help reduce the memory footprint

8
8
2


Get num of elements in array


In [21]:
print(a.size)
print(b.size)
print(c.size)

3
6
3


Get total size of array (num of elements \* mem_size)


In [25]:
print(f'{a.size * a.itemsize} bytes')
print(f'{b.size * b.itemsize} bytes')
print(f'{c.size * c.itemsize} bytes')

24 bytes
48 bytes
6 bytes


In [26]:
# Simpler way to do the above
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)

24
48
6
